name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: windows
          - os: ubuntu-latest
            name: linux
          - os: macos-latest
            name: macos
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - run: pip install -r requirements.txt pyinstaller Pillow
    - run: pyinstaller main.py --onefile --collect-data=grapheme --copy-metadata readchar --name=ncp-${{ matrix.name }} --hidden-import util.inquirer_console_render
    - run: ./dist/ncp-${{ matrix.name }} --help
    - run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "sha_short=$(git rev-parse --short HEAD)" >> $env:GITHUB_ENV
    - uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        name: Release ${{ env.sha_short }}
        tag_name: ${{ env.sha_short }}
        token: ${{ secrets.GITHUB_TOKEN }}