name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: windows
          - os: ubuntu-latest
            name: linux
          - os: macos-latest
            name: macos
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - run: pip install -r requirements.txt pyinstaller Pillow
    - run: pyinstaller main.py --onefile --collect-data=grapheme --name=ncp-${{ matrix.name }}
    - run: ./dist/ncp-${{ matrix.name }} --help
    - id: vars
      run: |
        if [[ ${{ matrix.os }} == 'windows-latest' ]]; then
          set sha_short=$(git rev-parse --short HEAD)
        else
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        fi
    - uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        name: Release ${{ steps.vars.outputs.sha_short }}
        tag_name: ${{ steps.vars.outputs.sha_short }}
        token: ${{ secrets.GITHUB_TOKEN }}