name: Build

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - run: pip install -r requirements.txt pyinstaller Pillow
    - run: pyinstaller main.py --onefile --collect-data=grapheme --name=ncp-${{ matrix.os }} --icon=ncp.ico
    - run: ./dist/ncp-${{ matrix.os }} -v
    - uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        tag_name: ${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
