name: Build

on:
  push:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: windows
          - os: ubuntu-latest
            name: ubuntu
          - os: macos-latest
            name: macos
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - run: pip install -r requirements.txt pyinstaller Pillow
    - run: pyinstaller main.py --onefile --collect-data=grapheme --name=ncp-${{ matrix.name }} --icon=ncp.ico
    - run: ./dist/ncp-${{ matrix.name }} -v
    - uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        tag_name: ${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}
